
# MY custom kitty config
font_size                   11
disable_ligatures           never
# Fonts
font_family                 JetBrains Mono
bold_font                   auto
italic_font                 auto
bold_italic_font            auto

# color scheme
# background                  #0A0C0C
background_opacity          1

# Process hyperlinks so that urls become clickable links
allow_hyperlinks 	    yes


# BEGIN_KITTY_THEME
# Gruvbox Dark Hard
include current-theme.conf
# END_KITTY_THEME
